package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/*@author jjvg_*/
public class JFrmCausa extends javax.swing.JFrame {

    public JFrmCausa() {
        initComponents();
    }

    public JButton getCancelar() {
        return Cancelar;
    }

    public void setCancelar(JButton Cancelar) {
        this.Cancelar = Cancelar;
    }

    public JButton getBtnCaGuardar() {
        return btnCaGuardar;
    }

    public void setBtnCaGuardar(JButton btnCaGuardar) {
        this.btnCaGuardar = btnCaGuardar;
    }

  
    public JButton getBtnCaSalir() {
        return btnCaSalir;
    }

    public void setBtnCaSalir(JButton btnCaSalir) {
        this.btnCaSalir = btnCaSalir;
    }

    public JTextField getTxtCaCodigo1() {
        return txtCaCodigo1;
    }

    public void setTxtCaCodigo1(JTextField txtCaCodigo1) {
        this.txtCaCodigo1 = txtCaCodigo1;
    }

    public JTextField getTxtCaDescrip() {
        return txtCaDescrip;
    }

    public void setTxtCaDescrip(JTextField txtCaDescrip) {
        this.txtCaDescrip = txtCaDescrip;
    }

    public JTextField getTxtCaDuracion() {
        return txtCaDuracion;
    }

    public void setTxtCaDuracion(JTextField txtCaDuracion) {
        this.txtCaDuracion = txtCaDuracion;
    }

    public JTextField getTxtCaNombre() {
        return txtCaNombre;
    }

    public void setTxtCaNombre(JTextField txtCaNombre) {
        this.txtCaNombre = txtCaNombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmCausa = new javax.swing.JPanel();
        lblCaCodigo = new javax.swing.JLabel();
        lblCaDuracion = new javax.swing.JLabel();
        lblCaDescrip = new javax.swing.JLabel();
        lblCaNombre = new javax.swing.JLabel();
        txtCaNombre = new javax.swing.JTextField();
        txtCaCodigo1 = new javax.swing.JTextField();
        txtCaDuracion = new javax.swing.JTextField();
        txtCaDescrip = new javax.swing.JTextField();
        frmCaOpciones = new javax.swing.JPanel();
        btnCaGuardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        btnCaSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmCausa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAUSAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        lblCaCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaCodigo.setText("Codigo");

        lblCaDuracion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaDuracion.setText("Dias de Duracion");

        lblCaDescrip.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaDescrip.setText("Descripcion");

        lblCaNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaNombre.setText("Nombre");

        txtCaNombre.setEnabled(false);

        txtCaDuracion.setEnabled(false);

        txtCaDescrip.setEnabled(false);

        javax.swing.GroupLayout frmCausaLayout = new javax.swing.GroupLayout(frmCausa);
        frmCausa.setLayout(frmCausaLayout);
        frmCausaLayout.setHorizontalGroup(
            frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCausaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCausaLayout.createSequentialGroup()
                        .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCaCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCaCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaNombre))
                        .addGap(52, 52, 52))
                    .addGroup(frmCausaLayout.createSequentialGroup()
                        .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCaDuracion)
                            .addComponent(txtCaDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaDescrip))
                .addGap(28, 28, 28))
        );
        frmCausaLayout.setVerticalGroup(
            frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCausaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaCodigo)
                    .addComponent(lblCaNombre)
                    .addComponent(lblCaDescrip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmCausaLayout.createSequentialGroup()
                        .addGroup(frmCausaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCaCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lblCaDuracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCaDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        frmCaOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnCaGuardar.setText("Guardar");

        Cancelar.setText("Cancelar");

        btnCaSalir.setText("Salir");

        javax.swing.GroupLayout frmCaOpcionesLayout = new javax.swing.GroupLayout(frmCaOpciones);
        frmCaOpciones.setLayout(frmCaOpcionesLayout);
        frmCaOpcionesLayout.setHorizontalGroup(
            frmCaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCaOpcionesLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnCaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Cancelar)
                .addGap(33, 33, 33)
                .addComponent(btnCaSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );
        frmCaOpcionesLayout.setVerticalGroup(
            frmCaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmCaOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmCaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaGuardar)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCaSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmCausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frmCaOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmCausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(frmCaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void agregarListener (ActionListener accion)
{
   
    this.btnCaGuardar.addActionListener(accion);
    this.btnCaSalir.addActionListener(accion);
    this.Cancelar.addActionListener(accion);
}
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnCaGuardar;
    private javax.swing.JButton btnCaSalir;
    private javax.swing.JPanel frmCaOpciones;
    private javax.swing.JPanel frmCausa;
    private javax.swing.JLabel lblCaCodigo;
    private javax.swing.JLabel lblCaDescrip;
    private javax.swing.JLabel lblCaDuracion;
    private javax.swing.JLabel lblCaNombre;
    private javax.swing.JTextField txtCaCodigo1;
    private javax.swing.JTextField txtCaDescrip;
    private javax.swing.JTextField txtCaDuracion;
    private javax.swing.JTextField txtCaNombre;
    // End of variables declaration//GEN-END:variables

  
}
